services:
  bot:
    build: .
    container_name: media_download_bot
    restart: always
    volumes:
      - ./downloads:/app/downloads
      - ./logs:/app/logs
      - ./instagram_cookies.txt:/app/instagram_cookies.txt
    env_file:
      - .env
